### ISSUE TITLE
Compress assets

### ISSUE THREAD

**Issue by wrussell1999** [HackQuarantine/hq-website#46]
Page loads slowly due to lots of assets

**Comment by bahorn** [comment]
Going to check into a plugin for this. Seems to be a few around

**Comment by wrussell1999** [comment]
I'm compressing some of the team photos. Also, the Platter.dev one is quite large

**Comment by bahorn** [comment]
I'm setting up a plugin to handle it automatically for us

**Comment by bahorn** [comment]
so that ended up being too much of a hassle, optimizing assets locally then pushing.

**Comment by danielfspencer** [comment]
#50 resolves this
